# Generated by Django 5.1.4 on 2025-01-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_locking_delete_logging'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locking',
            options={},
        ),
    ]
