# Generated by Django 5.1.4 on 2025-01-14 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_locking_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locking',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='locking',
            table=None,
        ),
    ]
