# Generated by Django 5.1.4 on 2025-01-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_locking_locked_by_alter_locking_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locking',
            options={'managed': False},
        ),
    ]
