# Generated by Django 5.1.4 on 2025-01-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_locking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locking',
            options={},
        ),
    ]
