# Generated by Django 5.1.4 on 2025-01-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_locking_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locking',
            name='id',
        ),
        migrations.AlterField(
            model_name='locking',
            name='task_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
