# Generated by Django 5.1.4 on 2025-01-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='disk',
            field=models.CharField(max_length=191, null=True),
        ),
    ]
