# Generated by Django 5.1.4 on 2025-01-16 15:46

import modules.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_disk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='size',
            field=models.PositiveBigIntegerField(validators=[modules.media.models.validate_file_size]),
        ),
    ]
